### PR TITLE
Add MIN_POOL_SIZE environment variable and implement pool size check

### PR DESCRIPTION
**Pull request by Journeytojah**
Added a filter to check pool size at launch.

image

Also added `pnpm-lock.yaml` to gitignore for my commits.

### CODE REVIEW

**Comment by CHToken** [comment]
Nice update pushed, let's wait for the merge

**Comment by DevSolana** [comment]
Nice

**Comment by 0xArmz** [comment]
Can you add slipage function?

**Comment by DevSolana** [comment]
The code need to be updated.
If the pool is not yet launched :
[19:24:22.022] WARN: Skipping pool, smaller than 600 SOL
    mint: "HNDnoyG8TPw8U7FV2npitEox3LDQ21UpdjsFQ3Xb4sHo"
    pooled: "0 SOL"

After launch Pooled SOL
301.76
$52K

**Comment by shakilkhan1801** [comment]
I have sol in my wallet but I couldn't swap Sol to WSOL anywhere despite trying. And meanwhile the code is telling me I don't have Sol in my wallet. Please give option to use native sol instead of Wsol.

**Comment by RedWilly** [comment]
> The code need to be updated. If the pool is not yet launched :
> 
> ```
> [19:24:22.022] WARN: Skipping pool, smaller than 20 SOL
>     mint: "HNDnoyG8TPw8U7FV2npitEox3LDQ21UpdjsFQ3Xb4sHo"
>     pooled: "0 SOL"
> ```
> 
> After launch Pooled SOL 301.76 $52K

well this true another way to deal with this is 
set it that if the pool is 
0.000000000 SOL then wait for some time then check again ( but the issue with this is that  - we cant tell when the pool will launch )  unless we are able to tell when the pool is launch there is nothing that can be done unless constant check in that token every single minute..

**Comment by DevSolana** [comment]
> > Le code doit être mis à jour. Si le pool n'est pas encore lancé :
> > ```
> > [19:24:22.022] WARN: Skipping pool, smaller than 20 SOL
> >     mint: "HNDnoyG8TPw8U7FV2npitEox3LDQ21UpdjsFQ3Xb4sHo"
> >     pooled: "0 SOL"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Après le lancement Pooled SOL 301,76 52 000 $
> 
> eh bien, c'est vrai, une autre façon de gérer cela est de définir que si le pool est à 0,000000000 SOL, attendez un certain temps, puis vérifiez à nouveau (mais le problème est que - nous ne pouvons pas dire quand le pool sera lancé) à moins que nous puissions le faire. dire quand le pool est lancé, il n'y a rien à faire à moins de vérifier constamment ce jeton toutes les minutes.

There is a bot that retrieves the launch time, but I don't know how to do it. (yet)

**Pull request merged**
