### PR TITLE
Refactor project

### PR DESCRIPTION
**Pull request by NonVideri**
- Add type checking utility
- Make some refactoring changes

### CODE REVIEW

**Comment by CHToken** [comment]
This refactor is perfect and it's makes the buy.ts more readable

**Comment by benjiqq** [comment]
looks good. I have some more refactor suggestions, making the listeners their own functions in https://github.com/fdundjer/solana-sniper-bot/pull/68

**Comment by shakilkhan1801** [comment]
I have sol in my wallet but I couldn't swap Sol to WSOL anywhere despite trying. And meanwhile the code is telling me I don't have Sol in my wallet. Please give option to use native sol instead of Wsol.

**Comment by NonVideri** [comment]
> I have sol in my wallet but I couldn't swap Sol to WSOL anywhere despite trying. And meanwhile the code is telling me I don't have Sol in my wallet. Please give option to use native sol instead of Wsol.

You can import your key into Phantom wallet and easily wrap a chosen amount of SOL into WSOL.

Using native SOL would probably add quite a bit of complexity, and make the bot slower. It's also not really necessary, as wrapping is easy, and it allows you to control how much of the wallet to use for buying vs for transaction fees. At the very least, it doesn't seem like a priority feature right now.

**Comment by virtuman** [comment]
i used `spl-token wrap` for wrapping, because I also couldn't find the option to wrap in phantom :)

**Comment by virtuman** [comment]
great and clean. i tested seems to work fine. any plans on merging?

**Comment by virtuman** [comment]
> > I have sol in my wallet but I couldn't swap Sol to WSOL anywhere despite trying. And meanwhile the code is telling me I don't have Sol in my wallet. Please give option to use native sol instead of Wsol.
> 
> You can import your key into Phantom wallet and easily wrap a chosen amount of SOL into WSOL.
> 
> Using native SOL would probably add quite a bit of complexity, and make the bot slower. It's also not really necessary, as wrapping is easy, and it allows you to control how much of the wallet to use for buying vs for transaction fees. At the very least, it doesn't seem like a priority feature right now.

this could be a startup option in the script, something that checks if WSOL doesn't exist, or low balance, then prompt user if they want to do a transfer with something like this:
https://scortik.com/token-program-on-the-solana-blockchain-using-javascript/

**Pull request merged**
